name: Android Appium Tests

on:
  schedule:
    - cron: '5 10 * * *'  # 10:05 UTC = 17:05 GMT+7
  workflow_dispatch:      # Cho phép chạy thủ công

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Tests
        run: mvn clean test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            test-output/
            appium.log