name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'oracle'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Build with Maven
      run: mvn compile
        
    - name: Run Tests  
      run: |
        mvn test -Dtest=VPA
      shell: cmd
