name: Android Appium Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install Appium
      run: |
        npm install -g appium
        appium driver install uiautomator2
        
    - name: Start Appium Server
      run: |
        appium &
        sleep 5
        
    - name: Run Tests
      run: mvn clean test
