name: Android Appium Tests
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile and Get Dependencies
        run: |
          C:\Windows\System32\cmd.exe /c "C:\apache-maven-3.9.9\bin\mvn.cmd" dependency:copy-dependencies -DoutputDirectory=target/dependencies
          C:\Windows\System32\cmd.exe /c "C:\apache-maven-3.9.9\bin\mvn.cmd" compiler:compile compiler:testCompile

      - name: Run Tests
        run: |
          C:\Windows\System32\cmd.exe /c java -cp "target/test-classes;target/classes;target/dependencies/*" org.testng.TestNG testng.xml