name: Android Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Clean Maven Cache
      run: |
        rm -rf ~/.m2/repository/org/seleniumhq/selenium/
        rm -rf ~/.m2/repository/io/appium/
        
    - name: Build with Maven
      run: mvn clean test
